### ISSUE TITLE
Error? 

### ISSUE THREAD

**Issue by ZEROOblivious** [IridiumLLC/CustomEnchants#1]
01.01 22:23:39 [Server] ERROR Could not pass event PlayerInteractEvent to CustomEnchants v3.6.7
01.01 22:23:39 [Server] INFO java.lang.NullPointerException: null
01.01 22:23:39 [Server] INFO at ca.thederpygolems.armorequip.ArmorType.matchType(ArmorType.java:31) ~[?:?]
01.01 22:23:39 [Server] INFO at ca.thederpygolems.armorequip.ArmorListener.playerInteractEvent(ArmorListener.java:258) ~[?:?]
01.01 22:23:39 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor444.execute(Unknown Source) ~[?:?]
01.01 22:23:39 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:443) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-238]
01.01 22:23:39 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by IridiumLLC** [comment]
Update to lastest version
